### ISSUE TITLE
Can't Italicized some keywords/attributes

### ISSUE THREAD

**Issue by glennraya** [SintrumIT/oceanic-next-italic#17]
How come some of the attributes and keywords of my code were not italicized? I have operator mono installed and properly specified it to my sublime preference? Do I need to perform other steps?

**Comment by sliepie** [comment]
Could you provide an example of the attributes and keywords, that you expect to be italicized?

**Comment by sliepie** [comment]
Closing this for now, since we need more info. Please reopen when you can provide more info.
