### ISSUE TITLE
Not all keywords are properly getting italicised

### ISSUE THREAD

**Issue by thisizkp** [SintrumIT/oceanic-next-italic#18]
<img width="487" alt="screen shot 2016-11-19 at 17 38 04" src="https://cloud.githubusercontent.com/assets/4737336/20455310/fa7bb0a0-ae7e-11e6-9fa0-a36de0ff1181.png">

**Comment by thisizkp** [comment]
also `function` keyword not getting italicised

**Comment by sliepie** [comment]
This is intended behavior

**Comment by thisizkp** [comment]
ideally when you use `operator mono` font in `atom` editor, it'll italicise even the `var` & `function` keywords ? right ?

**Comment by sliepie** [comment]
Which parts of the code that gets italicized by your editor (e.g. atom, vscode, sublime) depends entirely on the theme. 
Most themes are defined as a `textmate theme` aka `.tmTheme` files. A theme must specify how keywords, comments, etc are styled.

Below a snippet of the `Oceanic Next Italic` [tmTheme](https://github.com/SintrumIT/oceanic-next-italic/blob/master/Oceanic%20Next%20Italic.tmTheme#L59) file, as an example:
```xml
<dict>
  <key>name</key>
  <string>Comments</string>
  <key>scope</key>
  <string>comment, punctuation.definition.comment</string>
  <key>settings</key>
  <dict>
    <key>fontStyle</key>
    <string>italic</string>
    <key>foreground</key>
    <string>#65737e</string>
  </dict>
</dict>
<dict>
  <key>name</key>
  <string>Variable</string>
  <key>scope</key>
  <string>variable</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#CDD3DE</string>
  </dict>
</dict
```

**Comment by thisizkp** [comment]
@JarnoNijboer Thanks man, It's a great tip for customising themes. Would love to modify your theme a bit, will fork that 👍
