### ISSUE TITLE
Customize vscode workbench ?

### ISSUE THREAD

**Issue by jbrodriguez** [SintrumIT/oceanic-next-italic#24]
Hi,

Will you consider updating the vscode theme to support upcoming workbench theming ?

These are the relevant issues:
https://github.com/Microsoft/vscode/issues/3112
https://github.com/Microsoft/vscode/issues/23506

And somewhat related:
https://github.com/equinusocio/vsc-material-theme/issues/12

**Comment by zackkrida** [comment]
Would love to see this implemented!

**Comment by marcoms** [comment]
I've created an updated theme based on this one with extensive workspace theming - https://marketplace.visualstudio.com/items?itemName=marcoms.oceanic-plus

Let me know what you guys think
