### ISSUE TITLE
Tag White

### ISSUE THREAD

**Issue by EQuimper** [SintrumIT/oceanic-next-italic#6]
In the screenshot the div tag are withe but I get mine red I'm the only one with this ?

**Comment by ghost** [comment]
I assume you are using Atom or Sublime? The screenshot is taken from VS Code, which shows the colors a little bit different than Atom/Sublime
We have adjusted the original `Oceanic Next` theme to make some parts of the code to appear in italics, and we haven't changed any of the colors of the original theme.

We are aware that the current screenshot is not representative for Atom and Sublime, and we are working on creating specific screenshots for each editor.

If you want to see how the original theme looks like, you can take a look at the [orginal](https://github.com/voronianski/oceanic-next-color-scheme#screenshots) repo

**Comment by EQuimper** [comment]
Thank you

**Comment by EQuimper** [comment]
If you want help with the atom version I can change it for be like the screenshot.
